### ISSUE TITLE
Problems when running

### ISSUE THREAD

**Issue by NickCis** [aocmulti/dprun#2]
Hi, i'm trying to run `dprun`, but i couldn't really make start the game.

I've compiled it with MinGW GCC on Linux and i'm using that build in Windows.

```
PS C:\Users\nickcis\Downloads\dprun> .\bin\debug\dprun.exe --host --player "a-player-name" --application "{5DE93F3F-FC90-4ee1-AE5A-63DAFA055950}" --service-provider TCPIP
[print_address] address:
PS C:\Users\nickcis\Downloads\dprun>
```

I'm really not use to windows for developing, any help with debugging this will be appreciated!.

Thanks!

**Comment by goto-bus-stop** [comment]
Hmm lol, it may be the case that it works on Linux with Wine right now but not on Windows. I get the same in a Windows VM. Git Bash reports a segmentation fault.

**Comment by goto-bus-stop** [comment]
I found at least one issue running it with gdb:

https://github.com/playage/dprun/commit/741df1ab61512ba908a26b1fa45d69c9db3c56ee

it looks like Wine is not picky about which type of `free()` function you use, but Windows is. MSDN documents which function you need to use but i was stubborn lol. there may be more cases like this.

**Comment by NickCis** [comment]
Thanks, that worked (had to run dprun as administrator).

I managed to compile it under windows using mingw-w64`for windows, i'll update the readme and send a PR.

Makefile worked without any modification.
